config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'
  resources :products do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  # Validations
  validates_presence_of :name, :price, :sku
  validates_uniqueness_of :sku
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success, :warning, :danger, :info, :notice, :alert
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.paginate(page: params[:page], per_page: 10).order('id DESC')
  end

  def search
    url = params[:page_url].present? ? params[:page_url] : 'https://magento-test.finology.com.my/breathe-easy-tank.html'
    result = CrawlerService.scrap_data(url)
    @scrapping_products = result.last
    flash[:info] = result.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web Crawler</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="container mt-4">
<%= render 'shared/header' %>
<%= render 'shared/flash_message' %>
<div class="<%= user_signed_in? ? '' : 'instant-login-style' %>">
  <%= yield %>
</div>
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- For font awesome 5 -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
</body>
</html>

app/views/products/_product.html.erb
<div class="product-info">
  <label for=""> Name : <%= product.name %>  </label> <br/>
  <label for=""> Price : <%= product.price %>  </label> <br/>
  <label for=""> Description : <%= product.description.present? ? product.description : 'Description not found' %> </label> <br/>
  <label for=""> Extra information : <%= product.extra_information.present? ? product.extra_information : 'Extra information not found' %> </label>
</div>
<hr>

app/views/products/index.html.erb
<% if @products.present? %>
  <h4 class="border-bottom"> Products List : <small> Total(<%= Product.count %>) </small></h4>
  <%= render partial: 'products/product', collection: @products, cached: true %>
<% else %>
  <div class="alert alert-info">
    <h5> No Products Found !
      It is added the default url('https://magento-test.finology.com.my/breathe-easy-tank.html') from
      which page data scrapping should start <%= link_to 'Click Here', search_products_path %>
      or copy an url and paste into header input field to scrap data from your reference
      magento site('https://magento-test.finology.com.my').
    </h5>
  </div>
<% end %>
<%= will_paginate @products %>

app/views/products/search.html.erb
<div class="float-right">
  <%= link_to 'Go To Products List', products_path %>
</div>
<h4 class="border-bottom"> Crawler Result : <%= @scrapping_products.length %> </h4>
<%= render partial: 'products/product',
           collection: @scrapping_products,
           cached: true unless @scrapping_products.empty?%>

app/views/shared/_crawel_form.html.erb
<div class="col-md-12 p-0">
  <%= form_tag(search_products_path, method: :get) do %>
    <div class="text-right row">
      <%= text_field_tag :page_url,
                         nil,
                         class: 'form-control col-md-9',
                         placeholder: 'url like : https://magento-test.finology.com.my/breathe-easy-tank.html)' %>
      <%= submit_tag 'Submit', class: 'text-right btn btn-primary col-mf-3 text-right' %>
    </div>
  <% end %>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= value %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="col-md-12 row">
  <div class="col-md-2 p-0">
    <h4>
      <%= link_to 'Web Crawler', root_path %>
    </h4>
  </div>
  <div class="col-md-8 p-0">
    <%= render 'shared/crawel_form' if user_signed_in? %>
  </div>
  <div class="col-md-2 p-0">
    <%= render 'shared/log_in_out' %>
  </div>
</div>
<hr/>

app/views/shared/_log_in_out.html.erb
<div class="text-right">
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete, class: 'text-right' do %>
      Log Out
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, class: 'text-right' do %>
      Login
    <% end %>
  <% end %>
</div>